// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvJSQ5BN9X2K_Mi73ATT2reMVem8Y5nXU',
    appId: '1:881196199660:web:9e36624a6d8428a7be7fc9',
    messagingSenderId: '881196199660',
    projectId: 'boardgamescoreapp',
    authDomain: 'boardgamescoreapp.firebaseapp.com',
    storageBucket: 'boardgamescoreapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzq8xIDssu5AxfzuRZzFkqGyVH-J5_40E',
    appId: '1:881196199660:android:cdffb87c47f8b10bbe7fc9',
    messagingSenderId: '881196199660',
    projectId: 'boardgamescoreapp',
    storageBucket: 'boardgamescoreapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtAEm75f9bgzCWwA5OjtiMHix_f_6ZicU',
    appId: '1:881196199660:ios:e49cb3398e6fa0ffbe7fc9',
    messagingSenderId: '881196199660',
    projectId: 'boardgamescoreapp',
    storageBucket: 'boardgamescoreapp.firebasestorage.app',
    iosBundleId: 'com.example.gameScoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtAEm75f9bgzCWwA5OjtiMHix_f_6ZicU',
    appId: '1:881196199660:ios:e49cb3398e6fa0ffbe7fc9',
    messagingSenderId: '881196199660',
    projectId: 'boardgamescoreapp',
    storageBucket: 'boardgamescoreapp.firebasestorage.app',
    iosBundleId: 'com.example.gameScoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvJSQ5BN9X2K_Mi73ATT2reMVem8Y5nXU',
    appId: '1:881196199660:web:3936ad7d99dc7978be7fc9',
    messagingSenderId: '881196199660',
    projectId: 'boardgamescoreapp',
    authDomain: 'boardgamescoreapp.firebaseapp.com',
    storageBucket: 'boardgamescoreapp.firebasestorage.app',
  );
}
